### ISSUE TITLE
Many colors have poor colorblind contrast

### ISSUE THREAD

**Issue by arouinfar** [phetsims/nitroglycerin#12]
Discovered in https://github.com/phetsims/molecule-shapes/issues/153

The colors for the various elements are specified in https://github.com/phetsims/nitroglycerin/blob/master/js/Element.js#L71-L87, and appear to come from [CPK coloring or Jmol](https://en.wikipedia.org/wiki/CPK_coloring#Modern_variants).

```js

  Element.Ar = new Element( 'Ar', 97, 188, null, 39.948, '#FFAFAF' );
  Element.B = new Element( 'B', 85, 192, 2.04, 10.811, 'rgb(255,170,119)' ); // peach/salmon colored, CPK coloring
  Element.Be = new Element( 'Be', 105, 153, 1.57, 9.012182, '#c2ff00' ); // beryllium
  Element.Br = new Element( 'Br', 114, 185, 2.96, 79.904, 'rgb(190,30,20)' ); // brown
  Element.C = new Element( 'C', 77, 170, 2.55, 12.0107, 'rgb(178,178,178)' );
  Element.Cl = new Element( 'Cl', 100, 175, 3.16, 35.4527, 'rgb(153,242,57)' );
  Element.F = new Element( 'F', 72, 147, 3.98, 18.9984032, 'rgb(247,255,74)' );
  Element.H = new Element( 'H', 37, 120, 2.20, 1.00794, '#ffffff' );
  Element.I = new Element( 'I', 133, 198, 2.66, 126.90447, '#940094' ); // dark violet, CPK coloring
  Element.N = new Element( 'N', 75, 155, 3.04, 14.00674, '#0000ff' );
  Element.Ne = new Element( 'Ne', 69, 154, null, 20.1797, '#1AFFFB' );
  Element.O = new Element( 'O', 73, 152, 3.44, 15.9994, PhetColorScheme.RED_COLORBLIND );
  Element.P = new Element( 'P', 110, 180, 2.19, 30.973762, 'rgb(255,128,0)' );
  Element.S = new Element( 'S', 103, 180, 2.58, 32.066, 'rgb(212,181,59)' );
  Element.Si = new Element( 'Si', 118, 210, 1.90, 28.0855, 'rgb(240,200,160)' ); // tan, Jmol coloring listed from https://secure.wikimedia.org/wikipedia/en/wiki/CPK_coloring
  Element.Sn = new Element( 'Sn', 145, 217, 1.96, 118.710, '#668080' ); // tin
  Element.Xe = new Element( 'Xe', 108, 216, 2.60, 131.293, '#429eb0' );
```
There are some combinations which have poor colorblind contrast, particularly Be/Cl/F and O/P/S.
![image](https://user-images.githubusercontent.com/8419308/52978765-e06b9e80-338f-11e9-9bfe-3dae841c9374.png)
![image](https://user-images.githubusercontent.com/8419308/52978790-02652100-3390-11e9-8965-ae2d68b8beed.png)
![image](https://user-images.githubusercontent.com/8419308/52978801-0b55f280-3390-11e9-8c03-9a4c77270d51.png)

Oxygen is being represented by PhetColorScheme.RED_COLORBLIND `rgb(255,85,0)` instead of the more traditional `rgb(255, 0, 0)`, so I'll take that as evidence that we can slightly tweak some of the other colors to improve colorblind contrast.

Leaving self-assigned to experiment with the colors and recommend alternatives.

**Comment by arouinfar** [comment]
I've made changes to Be, F, Cl, and P, which improve the contrast in colorblind preview modes of Illustrator. Here are the updated colors:

- Element.Be: `rgb(194, 255, 95)`
- Element.Cl: `rgb(136, 242, 21)`
- Element.F: `rgb(245, 255, 36)`
- Element.P: `rgb(255, 154, 0)`

<img src="https://user-images.githubusercontent.com/8419308/53129927-2195b700-3526-11e9-9032-ff0a85c48487.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/53129883-ff039e00-3525-11e9-8d6a-723ad57a235d.png" width=200><img src="https://user-images.githubusercontent.com/8419308/53129915-1478c800-3526-11e9-9ee4-c605d1bd335d.png" width=200>

Assigning @jonathanolson, since he authored Element.js and is the responsible dev for Molecule Shapes. Also tagging https://github.com/phetsims/QA/issues/280 and https://github.com/phetsims/QA/issues/279, since this would be a relevant change before the next release of MS/MSB.

**Comment by jonathanolson** [comment]
Changes made, and patches moved to MS/MSB release branches.

**Comment by arouinfar** [comment]
Thanks @jonathanolson. I think this definitely improved contrast a bit in Molecule Shapes.
