### ISSUE TITLE
add Van der Waals radius to Element

### ISSUE THREAD

**Issue by jbphet** [phetsims/nitroglycerin#9]
A decision has been made to use the nitroglycerin repository for the atom information used in the States of Matter simulation and its derivatives, see https://github.com/phetsims/states-of-matter/issues/50.  In order to support this, the Element type must include the Van der Waals radius, and currently it only includes the covalent radius.  In discussing this, @pixelzoom said:

> If you do add something like vanDerWaalsRadius, then I recommend renaming radius to covalentRadius.

I'm planning on doing just that.

**Comment by jbphet** [comment]
The simulations that currently use the nitroglycerin repository and thus could be adversely affected by this change (if done incorrectly) are:

+ atomic-interactions
+ balancing-chemical-equations
+ beaker
+ beers-law-lab
+ build-a-molecule
+ concentration
+ molarity
+ molecule-polarity
+ molecule-shapes
+ molecules-and-light
+ reactants-products-and-leftovers
+ states-of-matter
+ states-of-matter-basics

I did a quick regression test on all of these to make sure that they at least launch, that all screens can be shown, and that any atoms that are depicted look reasonable.  All passed with the exception of molecule-shapes, which hits an exception when going into the screens.  I backed out the change of the field name, and the exception is still hit, so at this point I *think* the exception is unrelated to the change.  I'll assign to @jonathanolson for review so that he can review the changes and make sure that the change isn't causing issues in molecule-shapes.

@jonathanolson - when you're done, can you assign to @pixelzoom to check out the sims listed above that he is most familiar with?  Thanks.

**Comment by pixelzoom** [comment]
I inspected the following sims that use the nitroglycerin repository:

+ balancing-chemical-equations
+ beers-law-lab
+ concentration
+ molarity
+ molecule-polarity
+ reactants-products-and-leftovers

Of these, only `balancing-chemical-equations` and `reactants-products-and-leftovers` rely on Element. The others are using `ChemUtils`, which is unrelated.

In `balancing-chemical-equations` and `reactants-products-and-leftovers`, and problem would manifest itself in the radius of atoms by `AtomNode`.  I tested both sims, and didn't see any obvious problems.

So @jonathanolson ... No need to assign this to me when you've completed your inspection.

**Comment by jonathanolson** [comment]
Fixed diameter in NITROGLYCERIN/Atom, renamed it covalentDiameter, removed a deprecated test file in BAM that referenced radius, and fixed the BAM 3D view.

I think everything is good now, but when I work more on BAM, I'll take a more in-depth look. Closing.
